// Sanctum Vox — Accent & Dialect Data
// Each accent documented independently using Wells' Lexical Sets
// Sources: Wells 1982 Accents of English, Cruttenden/Gimson 2014, Lindsey 2019 English After RP, Collins/Mees 2019

const ACCENT_DATA = {
  accents: {

    'general-american': {
      name: 'General American',
      region: 'United States (Standard)',
      abbreviation: 'GenAm',
      difficulty: 0,
      description: 'The most widely understood American English accent, used as the broadcast standard. Rhotic, with merged cot-caught vowels in most speakers. This is the reference accent — other accents show their shifts relative to GenAm.',
      history: 'General American emerged as a standardised "neutral" American accent in the early 20th century, driven by broadcasting. Unlike RP, it was never deliberately codified — it represents the speech patterns common to the Midwest and West, minus regional markers. Its dominance in media has made it the default "American" accent worldwide.',
      keyFeatures: [
        { label: 'Rhotic', description: '/r/ pronounced in all positions (car, bird, letter)' },
        { label: 'Flapped /t/', description: '/t/ becomes [ɾ] between vowels (butter, water, city)' },
        { label: 'Cot-caught merger', description: '/ɑ/ and /ɔ/ merge for many speakers' },
        { label: 'BATH = TRAP', description: '/æ/ used in bath, ask, dance (not /ɑː/)' },
      ],
      lexicalSets: {
        KIT:     { ipa: 'ɪ', example: 'ship, kit, bridge', notes: 'Front lax vowel, shorter than FLEECE' },
        DRESS:   { ipa: 'ɛ', example: 'step, dress, neck', notes: 'Open-mid front vowel' },
        TRAP:    { ipa: 'æ', example: 'tap, trap, back', notes: 'Near-open front vowel; may raise before nasals in some regions' },
        LOT:     { ipa: 'ɑ', example: 'stop, lot, rob', notes: 'Open back unrounded; merges with THOUGHT for many speakers' },
        STRUT:   { ipa: 'ʌ', example: 'cup, strut, bus', notes: 'Open-mid central vowel' },
        FOOT:    { ipa: 'ʊ', example: 'put, foot, good', notes: 'Near-close near-back rounded vowel' },
        BATH:    { ipa: 'æ', example: 'staff, bath, dance', notes: 'Same as TRAP — no BATH broadening in GenAm' },
        CLOTH:   { ipa: 'ɔ~ɑ', example: 'cough, cloth, long', notes: 'Merging with LOT for many speakers (cot-caught merger)' },
        NURSE:   { ipa: 'ɝ', example: 'hurt, nurse, word', notes: 'R-coloured mid-central vowel; distinctive GenAm feature' },
        FLEECE:  { ipa: 'i', example: 'free, fleece, see', notes: 'Close front vowel; typically shorter than RP equivalent' },
        PALM:    { ipa: 'ɑ', example: 'father, palm, calm', notes: 'Same quality as LOT; open back unrounded' },
        THOUGHT: { ipa: 'ɔ~ɑ', example: 'taught, thought, law', notes: 'Merging with LOT for many speakers; distinguished in NYC, conservative dialects' },
        GOOSE:   { ipa: 'u', example: 'goose, food, blue', notes: 'Close back rounded; may front slightly after coronals' },
        FACE:    { ipa: 'eɪ', example: 'take, face, day', notes: 'Closing diphthong from mid-front position' },
        GOAT:    { ipa: 'oʊ', example: 'go, goat, show', notes: 'Closing diphthong with back rounded onset' },
        PRICE:   { ipa: 'aɪ', example: 'try, price, fly', notes: 'Wide diphthong from open position' },
        CHOICE:  { ipa: 'ɔɪ', example: 'boy, choice, joy', notes: 'Diphthong from rounded back position' },
        MOUTH:   { ipa: 'aʊ', example: 'now, mouth, how', notes: 'Wide diphthong to back rounded position' },
        NEAR:    { ipa: 'ɪɹ', example: 'beer, near, fear', notes: 'Front vowel plus rhotic; distinct from SQUARE' },
        SQUARE:  { ipa: 'ɛɹ', example: 'pair, square, care', notes: 'Mid-front vowel plus rhotic' },
        START:   { ipa: 'ɑɹ', example: 'far, start, car', notes: 'Open back vowel plus rhotic' },
        NORTH:   { ipa: 'ɔɹ', example: 'war, north, for', notes: 'Back rounded vowel plus rhotic; merging with FORCE' },
        FORCE:   { ipa: 'oɹ', example: 'four, force, more', notes: 'Mid-back rounded plus rhotic; merging with NORTH' },
        CURE:    { ipa: 'ʊɹ', example: 'poor, cure, sure', notes: 'Near-close back plus rhotic; merging with FORCE/NORTH for many' },
        happY:   { ipa: 'i', example: 'happy, city, lucky', notes: 'Free variant of FLEECE in unstressed position' },
        lettER:  { ipa: 'ɚ', example: 'letter, dinner, lunar', notes: 'R-coloured schwa; distinct from RP non-rhotic /ə/' },
        commA:   { ipa: 'ə', example: 'comma, sofa, about', notes: 'Mid-central reduced vowel' },
      },
      consonantFeatures: [
        { label: 'Rhotic /ɹ/', description: 'Post-alveolar approximant /ɹ/ in all positions — initial, medial, and post-vocalic (car, bird, letter)' },
        { label: 'Alveolar flapping', description: '/t/ and /d/ become alveolar tap [ɾ] between a stressed and unstressed vowel (butter, water, city, ladder)' },
        { label: 'Dark /l/', description: 'Velarised (dark) [ɫ] in most or all positions — unlike RP, which distinguishes clear [l] in onsets from dark [ɫ] in codas, GenAm tends toward velarisation even word-initially (Wells 1982, Ladefoged & Johnson)' },
        { label: 'Aspirated voiceless stops', description: '/p, t, k/ strongly aspirated word-initially (pin, top, car); unaspirated after /s/ (spin, stop, scar)' },
        { label: 'Yod-dropping', description: '/j/ deleted after alveolars: "tune" = /tun/ (not /tjun/), "dew" = /du/, "new" = /nu/' },
        { label: 'Glottal reinforcement of /t/', description: '/t/ realised as glottal stop [ʔ] before syllabic /n/: button [ˈbʌʔn̩], mountain [ˈmaʊnʔn̩], kitten [ˈkɪʔn̩]. Distinct from British T-glottaling.' },
      ],
      mergers: [
        { label: 'Cot-caught merger', description: 'LOT /ɑ/ and THOUGHT /ɔ/ merging to /ɑ/ for most speakers — "cot" and "caught" sound identical. Widespread west of the Appalachians.' },
        { label: 'Mary-merry-marry merger', description: 'SQUARE /ɛɹ/, DRESS+/ɹ/, and TRAP+/ɹ/ merge before /r/ — "Mary", "merry", and "marry" all pronounced /mɛɹi/.' },
        { label: 'NORTH-FORCE merger', description: 'NORTH /ɔɹ/ and FORCE /oɹ/ merging for most speakers — "horse" and "hoarse" identical.' },
        { label: 'CURE-FORCE merger', description: 'CURE /ʊɹ/ merging with NORTH/FORCE for many speakers — "poor" and "pour" becoming identical. "Sure" increasingly rhymes with "shore". Wells 1982, advancing in contemporary GenAm.' },
      ],
      distinctiveSounds: ['ɹ', 'æ', 'ɑ', 'ɝ'],
      prosody: {
        rhythm: 'Stress-timed — stressed syllables at roughly equal intervals, unstressed syllables compressed.',
        intonation: 'Falling pitch on statements. Rising pitch on yes/no questions. Moderate pitch range.',
        tempo: 'Moderate pace (roughly 150 words/minute in casual speech).',
        features: [
          'Strong vowel reduction in unstressed syllables (schwa dominates)',
          'Sentence stress on content words; function words weakened',
          'Final falling tone on declaratives',
        ],
      },
      exampleSentences: [
        { text: 'The water bottle is on the counter.', ipa: '/ðə ˈwɑɾɚ ˈbɑɾl̩ ɪz ɑn ðə ˈkaʊnɾɚ/', notes: 'Note flapped /t/ in "water", "bottle", and "counter". Rhotic /ɚ/ endings.' },
        { text: 'I can\'t park the car near the garden.', ipa: '/aɪ kænt pɑɹk ðə kɑɹ nɪɹ ðə ˈɡɑɹdən/', notes: 'All /r/ sounds pronounced. Short /æ/ in "can\'t". /ɑ/ in "park", "car", "garden".' },
        { text: 'She asked her father to dance at the party.', ipa: '/ʃi æskt hɝ ˈfɑðɚ tə dæns æt ðə ˈpɑɹɾi/', notes: 'BATH words ("asked", "dance") use /æ/, not /ɑː/. Rhotic "her", "father", "party".' },
      ],
      minimalPairs: [],
      famousSpeakers: [
        { name: 'Tom Hanks', note: 'Quintessential GenAm — clear, neutral, widely understood' },
        { name: 'Jennifer Aniston', note: 'Clean GenAm with no strong regional markers' },
        { name: 'Anderson Cooper', note: 'Broadcast standard GenAm' },
        { name: 'Meryl Streep', note: 'Natural accent is GenAm (New Jersey-raised but neutralised)' },
      ],
      regionalVariations: [],
      exercises: [
        { title: 'Rhotic /r/ Foundation', type: 'articulation', instructions: 'Curl your tongue back slightly so the tip points toward the hard palate WITHOUT touching it. Maintain this position while voicing. The sides of the tongue touch the upper molars.', drills: ['red', 'run', 'car', 'bird', 'letter', 'mirror', 'rural'] },
        { title: 'T-Flapping Drill', type: 'articulation', instructions: 'Between two vowels, /t/ becomes a quick tap [ɾ] — the tongue flicks the alveolar ridge once, like a very fast /d/. This is automatic in natural speech.', drills: ['butter → budder', 'water → wader', 'city → siddy', 'better → bedder', 'little → liddle'] },
        { title: 'Vowel Reduction Practice', type: 'prosody', instructions: 'In unstressed syllables, most vowels reduce to schwa /ə/. Practise saying these words with strong stress contrast.', drills: ['banana /bəˈnænə/', 'photograph /ˈfoʊɾəɡɹæf/', 'computer /kəmˈpjuɾɚ/', 'about /əˈbaʊt/'] },
      ],
      coachingNotes: 'GenAm is the baseline. Key characteristics: strong rhotic /r/ (tongue curls back), short /æ/ in BATH words, /ɑ/ for LOT/PALM. The flapped /t/ between vowels is essential — "butter" sounds like "budder". Jaw is relatively relaxed compared to RP.',
      practiceWords: ['butter', 'water', 'car', 'bird', 'bath', 'dance', 'thought', 'lot'],
      commonMistakes: ['Missing the rhotic /r/', 'Using British /ɒ/ for LOT words', 'Not flapping intervocalic /t/'],
    },

    'rp': {
      name: 'Received Pronunciation',
      region: 'England (Standard)',
      abbreviation: 'RP',
      difficulty: 3,
      description: 'The prestige accent of British English, traditionally associated with the educated classes, BBC broadcasting, and classical theatre. Non-rhotic with distinct long vowels and crisp consonants. Modern RP (also called Standard Southern British / SSB) has shifted considerably from the "posh" RP of the mid-20th century — the vowel system has undergone an anticlockwise chain shift, several diphthongs have monophthongised, and the overall delivery is more relaxed.',
      history: 'RP developed from the speech of the London-based ruling classes and was codified in the late 19th century by phonetician Daniel Jones. It became the accent of the BBC (earning the name "BBC English"), public schools, and the Royal Family. Today "Modern RP" (Lindsey\'s SSB) has shifted considerably — it is less "posh" than historical RP and is spoken by roughly 3% of the English population. Key changes documented by Lindsey (2019) include GOOSE fronting, TRAP lowering, DRESS lowering, SQUARE monophthongisation, and GOAT centralisation.',
      keyFeatures: [
        { label: 'Non-rhotic', description: '/r/ dropped after vowels (car → /kɑː/). Linking /r/ obligatory before vowels ("far away" = /fɑːr əˈweɪ/). Intrusive /r/ common ("law[r] and order").' },
        { label: 'BATH broadening', description: '/æ/ → /ɑː/ in bath, dance, ask — the TRAP-BATH split. THE defining RP marker vs GenAm.' },
        { label: 'LOT rounding', description: 'LOT uses rounded /ɒ/ — a short open rounded back vowel that does not exist in GenAm.' },
        { label: 'Crisp /t/', description: 'No flapping — /t/ is a full alveolar stop between vowels ("butter" = /ˈbʌtə/, not /ˈbʌɾɚ/). T-glottaling acceptable before consonants and utterance-finally.' },
        { label: 'Yod retention', description: '"tune" = /tjuːn/, "duke" = /djuːk/, "new" = /njuː/ — yod /j/ retained after alveolars where GenAm drops it.' },
      ],
      lexicalSets: {
        KIT:     { ipa: 'ɪ', example: 'ship, kit, bridge', notes: 'Short lax front vowel; clearly distinct from FLEECE. Somewhat centralised in modern SSB (Lindsey 2019). Wells 1982: /ɪ/.' },
        DRESS:   { ipa: 'e', example: 'step, dress, neck', notes: 'Traditional transcription /e/ (close-mid front). Modern SSB realisation is lowered to [ɛ] as part of the anticlockwise short vowel shift (Lindsey 2019). Actors will find /e/ in dictionaries but should aim for a slightly more open quality in natural modern RP.' },
        TRAP:    { ipa: 'æ', example: 'tap, trap, back', notes: 'Traditional transcription /æ/ (near-open front). Modern SSB has lowered this to fully open front [a] (Lindsey 2019, Cruttenden 2014). Distinct from BATH. Actors: dictionaries show /æ/ but the modern realisation is more open than GenAm /æ/.' },
        LOT:     { ipa: 'ɒ', example: 'stop, lot, rob', notes: 'Short open rounded back vowel — does NOT exist in GenAm. Modern SSB may raise toward [ɔ] (Lindsey 2019). Essential RP marker: lips must round. Wells 1982: /ɒ/.' },
        STRUT:   { ipa: 'ʌ', example: 'cup, strut, bus', notes: 'Traditional transcription /ʌ/ (open-mid back unrounded). Modern SSB realisation is more central [ə]-like quality (Lindsey 2019). The traditional symbol is kept in dictionaries. Wells 1982: /ʌ/.' },
        FOOT:    { ipa: 'ʊ', example: 'put, foot, good', notes: 'Near-close near-back rounded vowel. Fronted in modern SSB. Wells 1982: /ʊ/.' },
        BATH:    { ipa: 'ɑː', example: 'staff, bath, dance', notes: 'Long open back vowel — THE defining TRAP-BATH split. Same vowel as PALM and START. "Bath" = /bɑːθ/, "dance" = /dɑːns/, "ask" = /ɑːsk/. This is the single most important RP marker for American actors. Wells 1982: /ɑː/.' },
        CLOTH:   { ipa: 'ɒ', example: 'cough, cloth, long', notes: 'Same quality as LOT — short rounded back vowel. Wells 1982: /ɒ/.' },
        NURSE:   { ipa: 'ɜː', example: 'hurt, nurse, word', notes: 'Long open-mid central vowel. NON-RHOTIC — no tongue retroflexion or r-colouring. "Bird" = /bɜːd/, not /bɝːd/. Wells 1982: /ɜː/.' },
        FLEECE:  { ipa: 'iː', example: 'free, fleece, see', notes: 'Long close front vowel. Wells 1982: /iː/.' },
        PALM:    { ipa: 'ɑː', example: 'father, palm, calm', notes: 'Same quality as BATH and START — long open back vowel. Wells 1982: /ɑː/.' },
        THOUGHT: { ipa: 'ɔː', example: 'taught, thought, law', notes: 'Long open-mid rounded back vowel. Modern SSB raises toward [oː] (Lindsey 2019). Wells 1982: /ɔː/.' },
        GOOSE:   { ipa: 'uː', example: 'goose, food, blue', notes: 'Traditional transcription /uː/ (close back rounded). Significantly fronted in modern SSB to [ʉː] (Lindsey 2019, Cruttenden 2014). One of the most notable modern shifts. Wells 1982: /uː/.' },
        FACE:    { ipa: 'eɪ', example: 'take, face, day', notes: 'Closing diphthong from close-mid front. Modern SSB onset lowered to [ɛɪ] (Lindsey 2019). Wells 1982: /eɪ/.' },
        GOAT:    { ipa: 'əʊ', example: 'go, goat, show', notes: 'Closing diphthong with CENTRAL onset — distinct from GenAm /oʊ/ which has a BACK onset. This is a key diagnostic for RP vs GenAm. "Go" = /ɡəʊ/, NOT /ɡoʊ/. Wells 1982: /əʊ/.' },
        PRICE:   { ipa: 'aɪ', example: 'try, price, fly', notes: 'Wide diphthong from open position. Modern SSB backs the onset to [ɑɪ] (Lindsey 2019). Wells 1982: /aɪ/.' },
        CHOICE:  { ipa: 'ɔɪ', example: 'boy, choice, joy', notes: 'Diphthong from rounded back position. Wells 1982: /ɔɪ/.' },
        MOUTH:   { ipa: 'aʊ', example: 'now, mouth, how', notes: 'Wide diphthong with front onset [a]. In modern SSB, PRICE and MOUTH onsets have swapped relative to older RP: PRICE has backed to [ɑɪ] while MOUTH has fronted to [aʊ] at TRAP quality (Lindsey 2019). Wells 1982: /aʊ/.' },
        NEAR:    { ipa: 'ɪə', example: 'beer, near, fear', notes: 'Traditional centering diphthong /ɪə/. Modern SSB increasingly monophthongal [ɪː] (Lindsey 2019). NEAR-SQUARE merger in progress among younger speakers. Wells 1982: /ɪə/.' },
        SQUARE:  { ipa: 'ɛː', example: 'pair, square, care', notes: 'NOW a monophthong [ɛː] in modern SSB — the traditional diphthong /eə/ is outdated (Lindsey 2019, Cruttenden 2014). SQUARE monophthongisation is near-complete. Do NOT teach the old diphthong /eə/ for modern RP. Wells 1982 had /eə/ but this has shifted.' },
        START:   { ipa: 'ɑː', example: 'far, car, heart', notes: 'Same as BATH/PALM — long open back vowel. NON-RHOTIC: no /r/ following. "Car" = /kɑː/, "far" = /fɑː/. Wells 1982: /ɑː/.' },
        NORTH:   { ipa: 'ɔː', example: 'war, short, horse', notes: 'Same as THOUGHT — fully merged with FORCE. "Horse" and "hoarse" identical. Wells 1982: /ɔː/.' },
        FORCE:   { ipa: 'ɔː', example: 'four, more, hoarse', notes: 'Merged with NORTH — both /ɔː/. Historically distinct but merger now complete. Wells 1982: /ɔː/.' },
        CURE:    { ipa: 'ʊə', example: 'poor, cure, sure', notes: 'Traditional centering diphthong /ʊə/. Merging with THOUGHT /ɔː/ in modern SSB — "poor" increasingly /pɔː/ rather than /pʊə/ (Lindsey 2019, Cruttenden 2014). Advanced merger among younger speakers.' },
        happY:   { ipa: 'i', example: 'happy, city', notes: 'Free variant of FLEECE in word-final unstressed position. Wells 1982: /i/.' },
        lettER:  { ipa: 'ə', example: 'letter, dinner', notes: 'Plain schwa — NON-RHOTIC. No r-colouring whatsoever. "Letter" = /ˈletə/, not /ˈletɚ/. Wells 1982: /ə/.' },
        commA:   { ipa: 'ə', example: 'comma, sofa', notes: 'Mid-central reduced vowel; identical to lettER. Wells 1982: /ə/.' },
      },
      consonantFeatures: [
        { label: 'Non-rhotic', description: '/r/ only pronounced before vowels; silent after vowels (car /kɑː/, bird /bɜːd/). Linking /r/ is obligatory between a non-high vowel and a following vowel ("far away" /fɑːr əˈweɪ/). Intrusive /r/ common in natural speech ("law[r] and order", "idea[r] of"). Sources: Wells 1982, Cruttenden 2014.' },
        { label: 'Clear /t/ (no flapping)', description: 'No alveolar flapping — /t/ is a full, aspirated alveolar stop between vowels: "butter" /ˈbʌtə/, "water" /ˈwɔːtə/, "city" /ˈsɪti/. This is one of the most noticeable differences from GenAm. Aspirated word-initially.' },
        { label: 'T-glottaling', description: 'In modern RP, /t/ may be replaced by glottal stop [ʔ] before consonants ("football" [ˈfʊʔbɔːl]) and utterance-finally ("what" [wɒʔ]). Increasingly acceptable intervocalically in casual speech, though less so than in Estuary/Cockney. Cruttenden 2014, Lindsey 2019.' },
        { label: 'Clear and dark /l/ allophony', description: 'Clear [l] in onsets (light, play); dark velarised [ɫ] in codas (feel, milk). More distinct allophony than GenAm.' },
        { label: 'Yod retention', description: '/j/ retained after alveolar consonants: "tune" = /tjuːn/, "duke" = /djuːk/, "new" = /njuː/. GenAm drops yod in these contexts. Note: "suit" is now predominantly /suːt/ without yod (72% per 2008 Longman poll) — yod in "suit" is variable, not standard. Wells 1982.' },
      ],
      mergers: [
        { label: 'NORTH-FORCE merger', description: 'NORTH and FORCE fully merged to /ɔː/ — "horse" and "hoarse", "war" and "wore" identical. Complete in all modern RP speakers. Wells 1982.' },
        { label: 'CURE → THOUGHT merger', description: 'CURE /ʊə/ merging with THOUGHT /ɔː/ — "poor" increasingly /pɔː/ rather than /pʊə/. Advanced among younger speakers. Some words like "sure" now predominantly /ʃɔː/. Cruttenden 2014, Lindsey 2019.' },
        { label: 'NEAR-SQUARE distinction maintained', description: 'Contrary to some claims, NEAR and SQUARE are NOT merging in SSB — they are diverging. NEAR → [ɪː] (monophthongised from /ɪə/), SQUARE → [ɛː] (monophthongised from /eə/). These are phonetically distinct vowels. The NEAR-SQUARE merger is documented in New Zealand English but is not a feature of modern RP/SSB. Lindsey 2019.' },
        { label: 'SQUARE monophthongisation', description: 'The traditional diphthong /eə/ has become monophthong /ɛː/ for virtually all modern RP speakers. Near-complete. Lindsey 2019, Cruttenden 2014.' },
      ],
      distinctiveSounds: ['ɒ', 'ɑː', 'ɜː', 'əʊ', 'ɛː'],
      prosody: {
        rhythm: 'Stress-timed with strong reduction of unstressed syllables. More measured pace than GenAm.',
        intonation: 'Wider pitch range than GenAm. Falls decisively on statements. Pitch (not volume) is the primary means of emphasis — contrasts with GenAm which uses more volume. High-rising head on questions.',
        tempo: 'Moderate to deliberate. Tendency to slightly slower, more enunciated delivery than GenAm.',
        features: [
          'Falling-rising tone common for polite or tentative statements — the iconic British "hedge"',
          'Wider pitch range than GenAm — more melodic quality',
          'More measured tempo with clearer syllable boundaries',
          'Pitch used for emphasis rather than volume (GenAm favours volume)',
          'Clear distinction between strong and weak forms of function words',
          'Longer vowels in stressed positions',
        ],
      },
      exampleSentences: [
        { text: 'I can\'t park the car near the garden.', ipa: '/aɪ kɑːnt pɑːk ðə kɑː nɪə ðə ˈɡɑːdən/', notes: 'Non-rhotic: no /r/ in "park", "car", "garden", "near". BATH vowel /ɑː/ in "can\'t". Compare with GenAm /aɪ kænt pɑɹk ðə kɑɹ nɪɹ ðə ˈɡɑɹdən/.' },
        { text: 'The water bottle is on the counter.', ipa: '/ðə ˈwɔːtə ˈbɒtl̩ ɪz ɒn ðə ˈkaʊntə/', notes: 'Clear /t/ in "water" (no flap). Rounded /ɒ/ in "bottle" and "on". No final /r/ in "water" or "counter".' },
        { text: 'She asked her father to dance at the party.', ipa: '/ʃiː ɑːskt hɜː ˈfɑːðə tə dɑːns ət ðə ˈpɑːti/', notes: 'BATH broadening in "asked" /ɑːskt/, "dance" /dɑːns/. Long /ɑː/ throughout. Non-rhotic — no /r/ in "her", "father", "party".' },
        { text: 'The goat goes slowly down the road.', ipa: '/ðə ɡəʊt ɡəʊz ˈsləʊli daʊn ðə ɹəʊd/', notes: 'GOAT vowel /əʊ/ with central onset — NOT back /oʊ/ as in GenAm. Key diagnostic for RP.' },
      ],
      minimalPairs: [
        { word1: 'bath', pron1: '/bɑːθ/', word2: 'bath', pron2: '/bæθ/', label: 'RP vs GenAm', note: 'BATH broadening — the single most defining RP marker for American ears' },
        { word1: 'lot', pron1: '/lɒt/', word2: 'lot', pron2: '/lɑt/', label: 'RP vs GenAm', note: 'LOT rounding — RP uses rounded /ɒ/, GenAm uses unrounded /ɑ/' },
        { word1: 'butter', pron1: '/ˈbʌtə/', word2: 'butter', pron2: '/ˈbʌɾɚ/', label: 'RP vs GenAm', note: 'Clear /t/ vs flapped /ɾ/, plus non-rhotic /ə/ vs rhotic /ɚ/' },
        { word1: 'car', pron1: '/kɑː/', word2: 'car', pron2: '/kɑɹ/', label: 'RP vs GenAm', note: 'Non-rhotic vs rhotic' },
        { word1: 'goat', pron1: '/ɡəʊt/', word2: 'goat', pron2: '/ɡoʊt/', label: 'RP vs GenAm', note: 'Central onset /əʊ/ vs back onset /oʊ/ — key diagnostic' },
        { word1: 'tune', pron1: '/tjuːn/', word2: 'tune', pron2: '/tuːn/', label: 'RP vs GenAm', note: 'Yod retention in RP vs yod-dropping in GenAm' },
      ],
      famousSpeakers: [
        { name: 'David Attenborough', note: 'Classic RP with warm, measured delivery' },
        { name: 'Judi Dench', note: 'Modern RP — authoritative but not stiff' },
        { name: 'Benedict Cumberbatch', note: 'Contemporary modern RP, slightly relaxed' },
        { name: 'Emma Thompson', note: 'Educated RP with theatrical precision' },
      ],
      regionalVariations: [
        { name: 'Conservative RP', description: 'The older, "posher" form — associated with aristocracy and pre-1960s BBC. More central /ɑː/ quality (modern RP is more firmly back), NEAR and SQUARE clearly distinct as diphthongs, no GOOSE fronting. Rare today.' },
        { name: 'Modern RP / SSB', description: 'Today\'s standard (Lindsey\'s "Standard Southern British"). More relaxed, GOOSE fronted, SQUARE monophthongised, DRESS and TRAP lowered (anticlockwise shift). Incorporates some features like occasional t-glottaling.' },
        { name: 'Advanced RP', description: 'Hyper-refined form often parodied as "plummy". Exaggerated long vowels and diphthongs. Essentially extinct in natural speech.' },
      ],
      exercises: [
        { title: 'BATH Broadening Drill', type: 'vowel', instructions: 'Say each word first with GenAm /æ/, then with RP /ɑː/. Feel your jaw drop and tongue pull back. The vowel should be long and open — same quality as "father".', drills: ['bath /bæθ/ → /bɑːθ/', 'dance /dæns/ → /dɑːns/', 'ask /æsk/ → /ɑːsk/', 'grass /ɡɹæs/ → /ɡɹɑːs/', 'laugh /læf/ → /lɑːf/', 'can\'t /kænt/ → /kɑːnt/', 'half /hæf/ → /hɑːf/', 'past /pæst/ → /pɑːst/'] },
        { title: 'Non-rhotic Practice', type: 'consonant', instructions: 'Read each word/phrase. Keep your tongue FLAT — do not curl it back. The /r/ only appears before vowels (linking r). This is the hardest habit for Americans to break.', drills: ['car /kɑː/ (NOT /kɑɹ/)', 'park /pɑːk/ (NOT /pɑɹk/)', 'bird /bɜːd/ (NOT /bɝːd/)', 'letter /ˈletə/ (NOT /ˈletɚ/)', 'father /ˈfɑːðə/ (NOT /ˈfɑːðɚ/)', 'far away /fɑːr əˈweɪ/ (linking r — here /r/ IS pronounced)', 'law and order /lɔːr ənd ˈɔːdə/ (intrusive r)'] },
        { title: 'Clear /t/ Articulation', type: 'consonant', instructions: 'In RP, /t/ between vowels is NOT flapped. It is a full, aspirated stop. Touch your tongue firmly to the alveolar ridge and release with a small puff of air. Americans: this will feel exaggerated at first.', drills: ['butter /ˈbʌtə/ (NOT "budder")', 'water /ˈwɔːtə/ (NOT "wader")', 'city /ˈsɪti/ (NOT "siddy")', 'better /ˈbetə/ (NOT "bedder")', 'petal /ˈpetl̩/', 'matter /ˈmætə/'] },
        { title: 'GOAT Vowel — Central Onset', type: 'vowel', instructions: 'GenAm GOAT starts at back /o/ and glides to /ʊ/. RP GOAT starts in the CENTRE — begin with a schwa-like sound /ə/ and glide to /ʊ/. Your lips should NOT round at the start.', drills: ['go /ɡəʊ/ (NOT /ɡoʊ/)', 'goat /ɡəʊt/', 'show /ʃəʊ/', 'road /ɹəʊd/', 'home /həʊm/', 'no /nəʊ/', 'slow /sləʊ/'] },
        { title: 'LOT Rounding', type: 'vowel', instructions: 'GenAm LOT is unrounded /ɑ/ (jaw open, lips relaxed). RP LOT is rounded /ɒ/ — your lips must push forward into a slight "O" shape. The vowel is SHORT.', drills: ['lot /lɒt/', 'stop /stɒp/', 'hot /hɒt/', 'dog /dɒɡ/', 'on /ɒn/', 'gone /ɡɒn/', 'what /wɒt/', 'not /nɒt/'] },
        { title: 'Yod Retention', type: 'consonant', instructions: 'Where GenAm drops the /j/ sound after alveolar consonants, RP keeps it. Insert a quick "y" sound between the consonant and the /uː/.', drills: ['tune /tjuːn/ (NOT /tuːn/)', 'duke /djuːk/ (NOT /duːk/)', 'new /njuː/ (NOT /nuː/)', 'suit /suːt/ (yod now variable — /sjuːt/ is minority)', 'assume /əˈsjuːm/', 'student /ˈstjuːdənt/'] },
        { title: 'Sentence Drill — Putting It Together', type: 'integration', instructions: 'Read each sentence slowly, applying all RP features: non-rhotic, BATH broadening, LOT rounding, GOAT centralisation, clear /t/. Then gradually speed up while maintaining the accent.', drills: ['Father asked Charles to park the car by the castle. /ˈfɑːðər ɑːskt tʃɑːlz tə pɑːk ðə kɑː baɪ ðə ˈkɑːsl̩/', 'Rather a lot of water, I thought. /ˈɹɑːðər ə lɒt əv ˈwɔːtə aɪ θɔːt/', 'Pass the last glass, if you please. /pɑːs ðə lɑːst ɡlɑːs ɪf jə pliːz/', 'I don\'t know where the goat goes. /aɪ dəʊnt nəʊ weə ðə ɡəʊt ɡəʊz/'] },
      ],
      coachingNotes: 'For American actors, tackle these in order of impact: (1) Drop post-vocalic /r/ — this is the hardest habit to break. Practise "car park" as /kɑː pɑːk/ with NO tongue curl. (2) BATH broadening — use /ɑː/ in bath, dance, ask, can\'t, half, past. Same vowel as "father". (3) GOAT vowel — use central onset /əʊ/, NOT back /oʊ/. (4) Stop flapping /t/ — "butter" has a full /t/. (5) LOT rounding — round your lips for /ɒ/. (6) Add linking /r/ when the next word starts with a vowel ("far away" = /fɑːr əweɪ/). Common overcorrection: sounding "posh" — modern RP is relaxed, not exaggerated. Think Benedict Cumberbatch, not Queen Victoria.',
      practiceWords: ['bath', 'car', 'lot', 'butter', 'rather', 'thought', 'bird', 'goat', 'tune', 'dance'],
      commonMistakes: [
        'Not dropping post-vocalic /r/ — the #1 giveaway for American actors',
        'Using /æ/ in BATH words instead of /ɑː/ — "dance" must be /dɑːns/',
        'Using GenAm back /oʊ/ for GOAT instead of central /əʊ/',
        'Flapping /t/ between vowels — "water" must NOT sound like "wader"',
        'Over-articulating into "posh" RP — modern RP is relaxed, not stiff',
        'Missing LOT rounding — /ɒ/ requires rounded lips',
        'Wrong PRICE onset — modern RP backs it toward /ɑɪ/',
        'Missing linking /r/ — "far away" MUST have /r/ before the vowel',
        'Teaching outdated SQUARE diphthong /eə/ — modern RP uses monophthong /ɛː/',
        'Ignoring prosodic patterns — RP uses pitch (not volume) for emphasis, with wider pitch range than GenAm',
      ],
    },

  }
};
