// IPA Sound Data Library for Sanctum Vox Interactive Articulator
// Each sound has articulatory parameters, examples, and coaching notes

const places = ['bilabial','labiodental','dental','alveolar','postalveolar','retroflex','palatal','velar','uvular','pharyngeal','glottal'];
const manners = ['plosive','nasal','trill','tap','fricative','lateral_fricative','approximant','lateral_approximant'];

// Helper to create a sound entry
function s(symbol, name, type, place, manner, voiced, articulators, airflow, examples, coaching_notes, similar_sounds, extra) {
  return { symbol, name, type, place, manner, voiced, nasalised: articulators.velum?.raised === false, articulators, airflow, examples, coaching_notes, similar_sounds, ...extra };
}

// Default articulators template
// NOTE: tongue_tip and tongue_blade are NOT included by default.
// Only sounds that actively use the tip/blade should define them.
// This allows the vocal-tract auto-derivation to handle passive tip/blade
// positioning correctly for vowels and body-active consonants.
const def = {
  tongue_body: { height: 0.35, frontness: 0.5 },
  tongue_root: { advancement: 0.5 },
  tongue_sides: { lowered: false },
  lips: { rounding: 0, openness: 0.3, protrusion: 0, spread: 0 },
  velum: { raised: true, height: 1.0 },
  jaw: { openness: 0.2 },
  vocal_folds: { vibrating: false }
};

function a(overrides) {
  const r = JSON.parse(JSON.stringify(def));
  for (const [k, v] of Object.entries(overrides)) {
    if (typeof v === 'object' && r[k]) Object.assign(r[k], v);
    else r[k] = v;
  }
  return r;
}

const sounds = {
// ===== PLOSIVES =====
'p': s('p','Voiceless bilabial plosive','consonant','bilabial','plosive',false,
  a({ lips:{rounding:0,openness:0,protrusion:0.1,spread:0}, velum:{raised:true,height:1}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'plosive_release',path:'oral',constriction_point:'bilabial'},
  {en:['pat','spin','cap'],fr:['papa','porte'],de:['Paar','Pappe'],es:['padre','pan'],it:['padre','pane'],ja:['pon'],zh:['p\u00E0 (怕)'],ar:['bab'],hi:['pal'],ru:['papa']},
  'Both lips press together firmly, then release with a burst of air. English /p/ is aspirated word-initially (puff of air after release). Unaspirated after /s/ (as in "spin"). Many languages use unaspirated /p/ — tell actors to hold a hand in front of their mouth and aim for NO air puff.',
  ['b','t','k']),

'b': s('b','Voiced bilabial plosive','consonant','bilabial','plosive',true,
  a({ lips:{rounding:0,openness:0,protrusion:0.1,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'plosive_release',path:'oral',constriction_point:'bilabial'},
  {en:['bat','cab','bubble'],fr:['bon','beau'],de:['Ball','Bett'],es:['bien','boca'],it:['bene','bello']},
  'Like /p/ but with vocal fold vibration. Lips seal completely. Spanish /b/ between vowels becomes a fricative [β] — lips approximate but don\'t fully close. Common mistake: English speakers may devoice final /b/.',
  ['p','β','m']),

't': s('t','Voiceless alveolar plosive','consonant','alveolar','plosive',false,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.60}, jaw:{openness:0.15}, vocal_folds:{vibrating:false} }),
  {type:'plosive_release',path:'oral',constriction_point:'alveolar_ridge'},
  {en:['top','butter','cat'],fr:['table','petit'],de:['Tag','Mutter'],es:['todo','gato'],it:['tutto','tempo']},
  'Tongue tip makes firm contact with the alveolar ridge. English /t/ is aspirated initially, unaspirated after /s/. Many languages use dental /t/ (tongue touches teeth) — English is distinctly alveolar. American English often flaps intervocalic /t/ to [ɾ].',
  ['d','ʈ','ɾ']),

'd': s('d','Voiced alveolar plosive','consonant','alveolar','plosive',true,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.60}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'plosive_release',path:'oral',constriction_point:'alveolar_ridge'},
  {en:['dog','ladder','bad'],fr:['dans','donner'],de:['da','Dach'],es:['donde','nada'],it:['due','dado']},
  'Like /t/ but voiced. Spanish /d/ between vowels becomes [ð] (like English "the"). Common mistake: English speakers devoice final /d/. In many Indian languages, dental /d̪/ is the default — the tongue touches the teeth.',
  ['t','ɖ','ð']),

'ʈ': s('ʈ','Voiceless retroflex plosive','consonant','retroflex','plosive',false,
  a({ tongue_tip:{target:'postalveolar',contact:true,x:0.73,y:1.0}, tongue_blade:{x:0.60,y:0.50}, tongue_body:{height:0.42,frontness:0.45}, jaw:{openness:0.15}, vocal_folds:{vibrating:false} }),
  {type:'plosive_release',path:'oral',constriction_point:'postalveolar'},
  {hi:['ṭak','paṭ'],ar:[],ru:[]},
  'The tongue tip curls back (retroflexes) to contact the post-alveolar region. Critical for Hindi and many South Asian languages. Tell actors to curl the tongue tip UP and BACK — it should feel like the underside of the tongue touches the roof. Very different from English /t/.',
  ['ɖ','t','d']),

'ɖ': s('ɖ','Voiced retroflex plosive','consonant','retroflex','plosive',true,
  a({ tongue_tip:{target:'postalveolar',contact:true,x:0.73,y:1.0}, tongue_blade:{x:0.60,y:0.50}, tongue_body:{height:0.42,frontness:0.45}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'plosive_release',path:'oral',constriction_point:'postalveolar'},
  {hi:['ḍal','gaḍ']},
  'Voiced version of /ʈ/. Tongue curls back to the same position. Essential for Hindi. The retroflex quality gives these sounds their characteristic "heavy" quality that English speakers often describe as sounding "Indian".',
  ['ʈ','d','ɽ']),

'c': s('c','Voiceless palatal plosive','consonant','palatal','plosive',false,
  a({ tongue_body:{height:0.72,frontness:0.80}, jaw:{openness:0.15}, vocal_folds:{vibrating:false} }),
  {type:'plosive_release',path:'oral',constriction_point:'palatal'},
  {hu:['tyúk'],cz:['ť']},
  'The tongue body (not tip) presses against the hard palate. Sounds somewhat like a /k/ made further forward, or a /t/ made further back. Found in Hungarian, Czech, and other languages. Not the same as English "ch".',
  ['ɟ','k','t']),

'ɟ': s('ɟ','Voiced palatal plosive','consonant','palatal','plosive',true,
  a({ tongue_body:{height:0.72,frontness:0.80}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'plosive_release',path:'oral',constriction_point:'palatal'},
  {hu:['gyár'],cz:['ď']},
  'Voiced counterpart of /c/. Tongue body contacts hard palate. Can sound like a very fronted /ɡ/ or a backed /d/. Hungarian "gy" is this sound.',
  ['c','ɡ','d']),

'k': s('k','Voiceless velar plosive','consonant','velar','plosive',false,
  a({ tongue_body:{height:0.65,frontness:0.30}, jaw:{openness:0.15}, vocal_folds:{vibrating:false} }),
  {type:'plosive_release',path:'oral',constriction_point:'velar'},
  {en:['cat','skill','back'],fr:['cas','coq'],de:['Kind','Karte'],es:['casa','que'],it:['casa','che'],ja:['kaki'],zh:['kā (咖)']},
  'Back of tongue contacts the soft palate (velum). Aspirated in English word-initially. Note: /k/ moves forward before front vowels (like "key") and back before back vowels (like "cool") — this is automatic coarticulation.',
  ['ɡ','q','c']),

'ɡ': s('ɡ','Voiced velar plosive','consonant','velar','plosive',true,
  a({ tongue_body:{height:0.65,frontness:0.30}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'plosive_release',path:'oral',constriction_point:'velar'},
  {en:['go','bigger','dog'],fr:['gare','gout'],de:['gut','Geld'],es:['gato','algo'],it:['gatto','grande']},
  'Voiced /k/. Back of tongue contacts velum. Spanish /ɡ/ between vowels becomes [ɣ] (velar fricative). Common final devoicing in German — "Tag" ends with [k] not [ɡ].',
  ['k','ɣ','ŋ']),

'q': s('q','Voiceless uvular plosive','consonant','uvular','plosive',false,
  a({ tongue_body:{height:0.58,frontness:0.15}, tongue_root:{advancement:0.35}, jaw:{openness:0.2}, vocal_folds:{vibrating:false} }),
  {type:'plosive_release',path:'oral',constriction_point:'uvular'},
  {ar:['qalb','qalam']},
  'Back of tongue contacts the uvula — even further back than /k/. Critical for Arabic. The sound has a "deeper" quality than /k/. Tell actors to try saying /k/ while pushing the tongue as far back as possible. The pharynx narrows slightly.',
  ['ɢ','k','χ']),

'ɢ': s('ɢ','Voiced uvular plosive','consonant','uvular','plosive',true,
  a({ tongue_body:{height:0.58,frontness:0.15}, tongue_root:{advancement:0.35}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'plosive_release',path:'oral',constriction_point:'uvular'},
  {},
  'Voiced counterpart of /q/. Rare in world languages. Tongue back contacts uvula with voicing. Some Inuit languages use this sound.',
  ['q','ɡ','ʁ']),

'ʔ': s('ʔ','Glottal stop','consonant','glottal','plosive',false,
  a({ vocal_folds:{vibrating:false}, jaw:{openness:0.2} }),
  {type:'plosive_release',path:'oral',constriction_point:'glottal'},
  {en:['uh-oh','button (Cockney)'],ar:['ʔamal'],de:['beachten']},
  'The vocal folds snap shut momentarily, blocking all airflow, then release. English speakers use this in "uh-oh" and often before initial vowels. Cockney and Estuary English replace /t/ with glottal stop. In Arabic, this is the letter hamza (ء). Tell actors: it\'s the catch in your throat before a cough.',
  ['h','ɦ']),

// ===== NASALS =====
'm': s('m','Voiced bilabial nasal','consonant','bilabial','nasal',true,
  a({ lips:{rounding:0,openness:0,protrusion:0,spread:0}, velum:{raised:false,height:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'nasal',path:'nasal',constriction_point:'bilabial'},
  {en:['man','hammer','sum'],fr:['main','maman'],de:['Mutter','Kamm'],es:['mama','cama'],it:['mamma','mare'],ja:['mame'],zh:['mā (妈)']},
  'Lips close (like /b/) but velum lowers so air exits through the nose. Continuous voiced sound. One of the most universal consonants — virtually every language has /m/.',
  ['n','ŋ','b']),

'ɱ': s('ɱ','Voiced labiodental nasal','consonant','labiodental','nasal',true,
  a({ lips:{rounding:0,openness:0.08,protrusion:0,spread:0}, velum:{raised:false,height:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'nasal',path:'nasal',constriction_point:'labiodental'},
  {en:['comfort','infant'],it:['inferno']},
  'Lower lip contacts upper teeth (like /f/ position) with nasal airflow. Usually occurs automatically before /f/ or /v/ in English — the "m" in "comfort" is actually [ɱ]. Actors rarely need to produce this consciously.',
  ['m','n','f']),

'n': s('n','Voiced alveolar nasal','consonant','alveolar','nasal',true,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.60}, velum:{raised:false,height:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'nasal',path:'nasal',constriction_point:'alveolar_ridge'},
  {en:['no','inner','sun'],fr:['non','bonne'],de:['nein','Sonne'],es:['no','cana'],it:['no','notte'],ja:['nani'],zh:['nǎ (哪)']},
  'Tongue tip on alveolar ridge (like /d/ position) with nasal airflow. Very common across languages. In many languages it\'s dental rather than alveolar — tongue touches teeth instead of the ridge behind them.',
  ['m','ŋ','ɳ','d']),

'ɳ': s('ɳ','Voiced retroflex nasal','consonant','retroflex','nasal',true,
  a({ tongue_tip:{target:'postalveolar',contact:true,x:0.73,y:1.0}, tongue_blade:{x:0.60,y:0.50}, tongue_body:{height:0.42,frontness:0.45}, velum:{raised:false,height:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'nasal',path:'nasal',constriction_point:'postalveolar'},
  {hi:['baṇ']},
  'Retroflex nasal — tongue curls back like /ɖ/ but with nasal airflow. Important in Hindi and other South Asian languages.',
  ['n','ɲ','ɖ']),

'ɲ': s('ɲ','Voiced palatal nasal','consonant','palatal','nasal',true,
  a({ tongue_body:{height:0.72,frontness:0.80}, velum:{raised:false,height:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'nasal',path:'nasal',constriction_point:'palatal'},
  {fr:['agneau','montagne'],es:['año','niño'],it:['gnocchi','ogni'],pt:['banho']},
  'Tongue body presses against hard palate with nasal airflow. Spanish ñ, French gn, Italian gn. Tell actors: say "n" but with the middle of your tongue pressed up against the roof of your mouth, like you\'re about to say "y".',
  ['n','ŋ','j']),

'ŋ': s('ŋ','Voiced velar nasal','consonant','velar','nasal',true,
  a({ tongue_body:{height:0.65,frontness:0.30}, velum:{raised:false,height:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'nasal',path:'nasal',constriction_point:'velar'},
  {en:['sing','think','finger'],de:['lang','Ding'],ja:['nihongo'],zh:['máng (忙)']},
  'Back of tongue contacts velum (like /ɡ/ position) with nasal airflow. English "ng" in "sing". Common mistake: adding a /ɡ/ or /k/ after it. In "singer" there is no /ɡ/, but in "finger" there is. Some dialects drop final /ŋ/ to /n/ ("singin\'").',
  ['n','m','ɡ']),

'ɴ': s('ɴ','Voiced uvular nasal','consonant','uvular','nasal',true,
  a({ tongue_body:{height:0.58,frontness:0.15}, tongue_root:{advancement:0.35}, velum:{raised:false,height:0}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'nasal',path:'nasal',constriction_point:'uvular'},
  {ja:['nihon (sometimes)']},
  'Tongue back contacts uvula with nasal airflow. Very rare as a distinct phoneme. Sometimes occurs in Japanese word-finally.',
  ['ŋ','q']),

// ===== TRILLS =====
'ʙ': s('ʙ','Voiced bilabial trill','consonant','bilabial','trill',true,
  a({ lips:{rounding:0,openness:0.05,protrusion:0.2,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'trill',path:'oral',constriction_point:'bilabial'},
  {},
  'Both lips vibrate rapidly. Very rare as a phoneme. Tell actors to blow air through loosely closed lips — like a horse snort or the sound children make playing with toy cars ("brrr"). Requires relaxed lips and good airflow.',
  ['b','r']),

'r': s('r','Voiced alveolar trill','consonant','alveolar','trill',true,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.55}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'trill',path:'oral',constriction_point:'alveolar_ridge'},
  {es:['perro','rojo'],it:['rosso','terra'],ru:['рука','ворота'],ar:['ra']},
  'The tongue tip vibrates rapidly against the alveolar ridge. The classic "rolled R". Key: the tongue must be RELAXED — tension kills the trill. Place the tip lightly against the ridge and blow air. Start with "ddd" rapidly, then relax into the trill. Spanish "rr" vs single "r" [ɾ] is a crucial distinction.',
  ['ɾ','ʀ','ɹ']),

'ʀ': s('ʀ','Voiced uvular trill','consonant','uvular','trill',true,
  a({ tongue_body:{height:0.58,frontness:0.18}, tongue_root:{advancement:0.35}, jaw:{openness:0.25}, vocal_folds:{vibrating:true} }),
  {type:'trill',path:'oral',constriction_point:'uvular'},
  {fr:['rouge (some dialects)'],de:['rot (some dialects)']},
  'The uvula vibrates against the back of the tongue. Some dialects of French and German use this. Similar to gargling. Tell actors to gargle gently with a bit of voice — that vibration is the uvular trill.',
  ['ʁ','r','χ']),

// ===== TAPS/FLAPS =====
'ⱱ': s('ⱱ','Voiced labiodental flap','consonant','labiodental','tap',true,
  a({ lips:{rounding:0,openness:0.15,protrusion:0,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'tap',path:'oral',constriction_point:'labiodental'},
  {},
  'Lower lip briefly strikes upper teeth and bounces away. Very rare. Found in some Central African languages.',
  ['v','f','b']),

'ɾ': s('ɾ','Voiced alveolar tap','consonant','alveolar','tap',true,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.55}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'tap',path:'oral',constriction_point:'alveolar_ridge'},
  {en:['butter (AmE)','ladder (AmE)'],es:['pero','cara'],it:['sera','caro'],ja:['ramen'],ko:['사람']},
  'A single quick tap of the tongue tip against the alveolar ridge. American English "tt" in "butter" and "dd" in "ladder". Spanish single "r" (pero vs perro). Japanese "r" is this sound. Tell actors: it\'s like a very fast, single /d/.',
  ['r','d','t']),

'ɽ': s('ɽ','Voiced retroflex flap','consonant','retroflex','tap',true,
  a({ tongue_tip:{target:'postalveolar',contact:true,x:0.73,y:1.0}, tongue_blade:{x:0.60,y:0.50}, tongue_body:{height:0.42,frontness:0.45}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'tap',path:'oral',constriction_point:'postalveolar'},
  {hi:['baṛa'],ur:['baṛa']},
  'Retroflex flap — tongue tip curls back then flaps forward past the post-alveolar region. Important in Hindi/Urdu. Sounds like a retroflex version of [ɾ].',
  ['ɾ','ɖ','ɳ']),

// ===== FRICATIVES =====
'ɸ': s('ɸ','Voiceless bilabial fricative','consonant','bilabial','fricative',false,
  a({ lips:{rounding:0,openness:0.05,protrusion:0.1,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'bilabial'},
  {ja:['fuji (ふじ)']},
  'Air forced between nearly-closed lips without them fully touching. Japanese "f" before "u" is this sound, not English /f/. Tell actors: blow gently through barely-parted lips, like blowing out a candle very softly.',
  ['β','f','p']),

'β': s('β','Voiced bilabial fricative','consonant','bilabial','fricative',true,
  a({ lips:{rounding:0,openness:0.05,protrusion:0.1,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'bilabial'},
  {es:['lobo','Cuba']},
  'Voiced version of /ɸ/. Lips approximate but don\'t touch, with voicing. Spanish /b/ between vowels is typically this sound. Tell actors: say /b/ but don\'t let your lips fully close — keep a tiny gap.',
  ['ɸ','b','v']),

'f': s('f','Voiceless labiodental fricative','consonant','labiodental','fricative',false,
  a({ lips:{rounding:0,openness:0.08,protrusion:0,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'labiodental'},
  {en:['fat','offer','leaf'],fr:['faire','effet'],de:['fahren','Affe'],es:['café (in some dialects)'],it:['fare','caffè']},
  'Lower lip lightly contacts upper teeth; air forces through the gap. Very common across European languages. Upper teeth should be visible resting on the lower lip.',
  ['v','ɸ','θ']),

'v': s('v','Voiced labiodental fricative','consonant','labiodental','fricative',true,
  a({ lips:{rounding:0,openness:0.08,protrusion:0,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'labiodental'},
  {en:['van','over','love'],fr:['vie','rêve'],de:['wir','Vase'],it:['vino','avere'],ru:['вода']},
  'Like /f/ but voiced. Lower lip against upper teeth with voicing. German "w" is /v/. Common mistake: speakers of languages without /v/ may substitute /w/ or /b/.',
  ['f','w','β']),

'θ': s('θ','Voiceless dental fricative','consonant','dental','fricative',false,
  a({ tongue_tip:{target:'dental',contact:false,x:1.05,y:0.80}, tongue_blade:{x:0.85,y:0.55}, tongue_body:{height:0.42,frontness:0.65}, lips:{rounding:0,openness:0.20,protrusion:0,spread:0.10}, jaw:{openness:0.18}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'dental'},
  {en:['thin','math','both'],es:['caza','cielo (Castilian)'],gr:['θάλασσα']},
  'Tongue tip protrudes slightly between upper and lower teeth or presses lightly against the back of the upper teeth. Air flows over the tongue tip. Found in English "th" (voiceless: "thin"). Many actors replace this with /f/ or /t/ — make sure the tongue tip is VISIBLE between the teeth, not tucked behind them.',
  ['ð','f','s','t']),

'ð': s('ð','Voiced dental fricative','consonant','dental','fricative',true,
  a({ tongue_tip:{target:'dental',contact:false,x:1.05,y:0.80}, tongue_blade:{x:0.85,y:0.55}, tongue_body:{height:0.42,frontness:0.65}, lips:{rounding:0,openness:0.20,protrusion:0,spread:0.10}, jaw:{openness:0.18}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'dental'},
  {en:['the','other','breathe'],es:['dedo','nada (in some dialects)']},
  'Voiced version of /θ/. English "th" in "the", "this", "other". Same tongue position as /θ/ but with voicing. Common mistake: replacing with /d/ or /z/. Spanish /d/ between vowels often becomes [ð].',
  ['θ','d','z']),

's': s('s','Voiceless alveolar fricative','consonant','alveolar','fricative',false,
  a({ tongue_tip:{target:'alveolar',contact:false,x:0.87,y:0.95}, tongue_blade:{x:0.72,y:0.65}, tongue_body:{height:0.48,frontness:0.62}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'alveolar'},
  {en:['see','mass','city'],fr:['sa','passer'],de:['Straße','wissen'],es:['si','casa'],it:['sera','passo'],ja:['sushi'],zh:['sī (丝)']},
  'Tongue tip approaches the alveolar ridge, creating a narrow groove down the centre of the tongue. Air is channeled through this groove producing a high-pitched hissing. The most common fricative in the world\'s languages. Key: the tongue groove must be narrow and centred.',
  ['z','ʃ','θ']),

'z': s('z','Voiced alveolar fricative','consonant','alveolar','fricative',true,
  a({ tongue_tip:{target:'alveolar',contact:false,x:0.87,y:0.95}, tongue_blade:{x:0.72,y:0.65}, tongue_body:{height:0.48,frontness:0.62}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'alveolar'},
  {en:['zoo','buzz','easy'],fr:['zéro','maison'],de:['sehr','Sonne'],it:['zero','rosa'],ru:['зуб']},
  'Voiced /s/. Same tongue position with voicing added. German word-initial "s" before vowels is /z/. Many languages lack /z/ entirely (Spanish, for instance). Common mistake for Spanish speakers: using /s/ where English requires /z/.',
  ['s','ʒ','ð']),

'ʃ': s('ʃ','Voiceless postalveolar fricative','consonant','postalveolar','fricative',false,
  a({ tongue_tip:{target:'postalveolar',contact:false,x:0.80,y:0.93}, tongue_blade:{x:0.70,y:0.65}, tongue_body:{height:0.55,frontness:0.55}, lips:{rounding:0.30,openness:0.15,protrusion:0.15,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'postalveolar'},
  {en:['she','mission','fish'],fr:['chat','machine'],de:['Schule','waschen'],it:['scena','pesce'],ja:['shika'],zh:['shī (诗)']},
  'Tongue blade rises toward the post-alveolar region. The tongue is flatter and further back than /s/, creating a broader, lower-pitched "shushing" sound. Lips are slightly rounded and protruded. Compare with /s/: "sip" vs "ship" — feel the tongue pull back and lips round.',
  ['ʒ','s','ʂ']),

'ʒ': s('ʒ','Voiced postalveolar fricative','consonant','postalveolar','fricative',true,
  a({ tongue_tip:{target:'postalveolar',contact:false,x:0.80,y:0.93}, tongue_blade:{x:0.70,y:0.65}, tongue_body:{height:0.55,frontness:0.55}, lips:{rounding:0.30,openness:0.15,protrusion:0.15,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'postalveolar'},
  {en:['measure','vision','beige'],fr:['je','rouge','jour'],pt:['jogo']},
  'Voiced /ʃ/. Same position with voicing. English "s" in "measure", "vision". French "j" is this sound. Rare word-initially in English but common in French.',
  ['ʃ','z','dʒ']),

'ʂ': s('ʂ','Voiceless retroflex fricative','consonant','retroflex','fricative',false,
  a({ tongue_tip:{target:'postalveolar',contact:false,x:0.73,y:0.94}, tongue_blade:{x:0.60,y:0.55}, tongue_body:{height:0.42,frontness:0.45}, jaw:{openness:0.15}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'postalveolar'},
  {zh:['shā (杀)'],ru:['шар'],pl:['szum']},
  'Tongue tip curls back toward post-alveolar area. Mandarin "sh", Russian "ш", Polish "sz". Sounds heavier/darker than /ʃ/.',
  ['ʐ','ʃ','s']),

'ʐ': s('ʐ','Voiced retroflex fricative','consonant','retroflex','fricative',true,
  a({ tongue_tip:{target:'postalveolar',contact:false,x:0.73,y:0.94}, tongue_blade:{x:0.60,y:0.55}, tongue_body:{height:0.42,frontness:0.45}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'postalveolar'},
  {zh:['rén (人)'],ru:['жар'],pl:['żaba']},
  'Voiced retroflex fricative. Mandarin "r" in some analyses, Russian "ж", Polish "ż/rz".',
  ['ʂ','ʒ','z']),

'ç': s('ç','Voiceless palatal fricative','consonant','palatal','fricative',false,
  a({ tongue_body:{height:0.70,frontness:0.80}, jaw:{openness:0.15}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'palatal'},
  {de:['ich','recht','Chemie'],ja:['hito (ひと)']},
  'Tongue body raises toward the hard palate. German "ch" after front vowels (ich, recht). Very different from the velar [x] after back vowels (ach, Buch). Tell actors: say "huge" and sustain the initial "h" — that friction is close to [ç]. Japanese "h" before "i" is this sound.',
  ['ʝ','x','ʃ']),

'ʝ': s('ʝ','Voiced palatal fricative','consonant','palatal','fricative',true,
  a({ tongue_body:{height:0.70,frontness:0.80}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'palatal'},
  {es:['yo (Rioplatense)'],gr:['γεια']},
  'Voiced version of /ç/. Argentine Spanish "y" and "ll" can be this sound. Like a very strong /j/ with audible friction.',
  ['ç','j','ʒ']),

'x': s('x','Voiceless velar fricative','consonant','velar','fricative',false,
  a({ tongue_body:{height:0.62,frontness:0.30}, jaw:{openness:0.2}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'velar'},
  {de:['Buch','ach','doch'],es:['jota','mujer'],ru:['хор'],sco:['loch'],ar:['خبز']},
  'Back of tongue approaches velum creating friction. German "ch" after back vowels (ach, Buch). Scottish "loch". Spanish "j". Tell actors: start from /k/ position but don\'t close fully — let air hiss through.',
  ['ɣ','ç','χ']),

'ɣ': s('ɣ','Voiced velar fricative','consonant','velar','fricative',true,
  a({ tongue_body:{height:0.62,frontness:0.30}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'velar'},
  {es:['agua','luego'],gr:['γάτα'],ar:['غريب']},
  'Voiced /x/. Spanish /ɡ/ between vowels becomes this. Arabic ghain (غ). Like /ɡ/ without full closure.',
  ['x','ɡ','ʁ']),

'χ': s('χ','Voiceless uvular fricative','consonant','uvular','fricative',false,
  a({ tongue_body:{height:0.58,frontness:0.18}, tongue_root:{advancement:0.35}, jaw:{openness:0.25}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'uvular'},
  {de:['Buch (some dialects)'],he:['חנוכה']},
  'Like /x/ but further back — at the uvula. Hebrew "ch" (chet). Sounds raspier/harsher than velar /x/.',
  ['ʁ','x','ħ']),

'ʁ': s('ʁ','Voiced uvular fricative','consonant','uvular','fricative',true,
  a({ tongue_body:{height:0.58,frontness:0.18}, tongue_root:{advancement:0.35}, jaw:{openness:0.25}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'uvular'},
  {fr:['rouge','Paris','rare'],de:['rot','Regen']},
  'The standard French and German "R". Back of tongue approaches uvula with voicing. NOT a trill for most speakers — it\'s a fricative or approximant. Tell actors: gargle gently while voicing. The friction should be at the very back of the mouth.',
  ['ʀ','χ','ɣ']),

'ħ': s('ħ','Voiceless pharyngeal fricative','consonant','pharyngeal','fricative',false,
  a({ tongue_body:{height:0.35,frontness:0.25}, tongue_root:{advancement:0.12}, jaw:{openness:0.30}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'pharyngeal'},
  {ar:['حب','حرب']},
  'Tongue root retracts to narrow the pharynx. Arabic ح (ha). Sounds like a very constricted, breathy "h". Tell actors: try whispering "ahhh" while squeezing the back of your throat. It should feel effortful.',
  ['ʕ','h','χ']),

'ʕ': s('ʕ','Voiced pharyngeal fricative','consonant','pharyngeal','fricative',true,
  a({ tongue_body:{height:0.35,frontness:0.25}, tongue_root:{advancement:0.12}, jaw:{openness:0.30}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'pharyngeal'},
  {ar:['عين','عرب']},
  'Voiced pharyngeal — Arabic ع (ain). One of the most difficult sounds for English speakers. The throat constricts heavily while voicing continues. It has a strained, squeezed quality. Tell actors: voice while squeezing your throat as if swallowing.',
  ['ħ','ɦ','h']),

'h': s('h','Voiceless glottal fricative','consonant','glottal','fricative',false,
  a({ jaw:{openness:0.25}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'glottal'},
  {en:['hat','ahead'],de:['Haus','Hund'],ja:['hana'],zh:['hē (喝)']},
  'Open vocal folds with air passing through — essentially a voiceless vowel. The tongue and lips take the shape of the following vowel. Many languages lack /h/ entirely (French, Italian). Common issue: "h-dropping" in many English dialects.',
  ['ɦ','ʔ']),

'ɦ': s('ɦ','Voiced glottal fricative','consonant','glottal','fricative',true,
  a({ jaw:{openness:0.25}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'glottal'},
  {en:['ahead (between vowels)'],cz:['hora'],hi:['haal']},
  'Breathy-voiced /h/. The vocal folds vibrate loosely. English /h/ between vowels is often this. Czech "h" is typically [ɦ].',
  ['h','ʔ']),

// ===== LATERAL FRICATIVES =====
'ɬ': s('ɬ','Voiceless alveolar lateral fricative','consonant','alveolar','lateral_fricative',false,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.60}, tongue_sides:{lowered:true}, jaw:{openness:0.15}, vocal_folds:{vibrating:false} }),
  {type:'fricative',path:'oral',constriction_point:'alveolar_lateral'},
  {cy:['llan','llwyd']},
  'Tongue tip contacts alveolar ridge (like /l/) but air is forced over the SIDES of the tongue with friction. Welsh "ll" (as in "Llanelli"). Tell actors: say /l/ and then blow hard — you should hear hissing air escape from the sides of the tongue.',
  ['ɮ','l','s']),

'ɮ': s('ɮ','Voiced alveolar lateral fricative','consonant','alveolar','lateral_fricative',true,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.60}, tongue_sides:{lowered:true}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'fricative',path:'oral',constriction_point:'alveolar_lateral'},
  {zu:['dla']},
  'Voiced version of /ɬ/. Found in Zulu and some other languages. Like a very "buzzy" /l/.',
  ['ɬ','l','z']),

// ===== APPROXIMANTS =====
'ʋ': s('ʋ','Voiced labiodental approximant','consonant','labiodental','approximant',true,
  a({ lips:{rounding:0,openness:0.12,protrusion:0,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'labiodental'},
  {hi:['vān'],fi:['vesi'],nl:['wijn']},
  'Lower lip approaches upper teeth without the friction of /v/. Hindi "v", Finnish "v", Dutch "w". Between English /v/ and /w/. Tell actors: start with /v/ position but back off — less contact, less friction.',
  ['v','w','f']),

'ɹ': s('ɹ','Voiced alveolar approximant','consonant','alveolar','approximant',true,
  a({ tongue_tip:{target:'postalveolar',contact:false,x:0.78,y:0.82}, tongue_blade:{x:0.65,y:0.65}, tongue_body:{height:0.50,frontness:0.50}, lips:{rounding:0.15,openness:0.20,protrusion:0.05,spread:0}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'postalveolar'},
  {en:['red','very','car (rhotic)']},
  'THE English "r" sound. Tongue tip raised toward (but not touching) the post-alveolar region. Lips slightly rounded. This is NOT a trill or tap — it\'s an approximant. Many English dialects are non-rhotic (no /ɹ/ in "car"). American English is strongly rhotic.',
  ['r','ɾ','ɻ','l']),

'ɻ': s('ɻ','Voiced retroflex approximant','consonant','retroflex','approximant',true,
  a({ tongue_tip:{target:'postalveolar',contact:false,x:0.72,y:0.80}, tongue_blade:{x:0.58,y:0.48}, tongue_body:{height:0.42,frontness:0.45}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'postalveolar'},
  {en:['red (some American dialects)'],zh:['ér (儿)']},
  'More retroflex version of /ɹ/. Some American English speakers and Mandarin "er" sound use this. Tongue curls back more than standard /ɹ/.',
  ['ɹ','ɽ','ʈ']),

'j': s('j','Voiced palatal approximant','consonant','palatal','approximant',true,
  a({ tongue_body:{height:0.68,frontness:0.8}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'palatal'},
  {en:['yes','you','beyond'],fr:['yeux','payer'],de:['ja','jemand'],es:['yo','maya'],it:['ieri'],ja:['yama']},
  'Tongue body rises high toward the hard palate without touching. English "y" in "yes". Essentially a non-syllabic /i/. German "j" is this sound (not English "j" which is /dʒ/). Very common cross-linguistically.',
  ['ʝ','i','ɥ']),

'ɰ': s('ɰ','Voiced velar approximant','consonant','velar','approximant',true,
  a({ tongue_body:{height:0.60,frontness:0.3}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'velar'},
  {ko:['의'],ja:['が (intervocalic)']},
  'Like /w/ without lip rounding. Tongue body approaches velum. Korean "ㅢ" involves this sound. Some analyses of Japanese intervocalic /ɡ/ describe it as this.',
  ['w','ɣ','j']),

// ===== LATERAL APPROXIMANTS =====
'l': s('l','Voiced alveolar lateral approximant','consonant','alveolar','lateral_approximant',true,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.60}, tongue_sides:{lowered:true}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'alveolar_lateral'},
  {en:['let','follow','call'],fr:['le','belle'],de:['laut','Ball'],es:['la','alto'],it:['la','bello'],ja:['(none — merged with ɾ)']},
  'Tongue tip contacts alveolar ridge while air flows over the lowered sides. English has "clear l" (before vowels: "let") and "dark l" (after vowels: "call" — tongue body pulls back). Many languages only have clear /l/. Japanese speakers often confuse /l/ and /ɹ/.',
  ['ɭ','ʎ','ɹ']),

'ɭ': s('ɭ','Voiced retroflex lateral approximant','consonant','retroflex','lateral_approximant',true,
  a({ tongue_tip:{target:'postalveolar',contact:true,x:0.73,y:1.0}, tongue_blade:{x:0.60,y:0.50}, tongue_body:{height:0.42,frontness:0.45}, tongue_sides:{lowered:true}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'postalveolar'},
  {hi:['baḷ']},
  'Retroflex lateral — tongue curls back like other retroflexes, with lateral airflow. Found in some Dravidian and Indo-Aryan languages.',
  ['l','ɽ','ɖ']),

'ʎ': s('ʎ','Voiced palatal lateral approximant','consonant','palatal','lateral_approximant',true,
  a({ tongue_body:{height:0.70,frontness:0.80}, tongue_sides:{lowered:true}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'palatal'},
  {it:['gli','figlio'],es:['llamar (traditional)'],pt:['filho']},
  'Tongue body contacts palate with lateral airflow. Italian "gli", traditional Castilian "ll" (now usually /ʝ/ or /j/). Tell actors: say /l/ while pressing the middle of your tongue against the roof of your mouth.',
  ['l','j','ɲ']),

'ʟ': s('ʟ','Voiced velar lateral approximant','consonant','velar','lateral_approximant',true,
  a({ tongue_body:{height:0.60,frontness:0.3}, tongue_sides:{lowered:true}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'velar'},
  {},
  'Very rare. Back of tongue contacts velum with lateral airflow. English "dark l" in some analyses approaches this. Some Papua New Guinean languages have it as a distinct phoneme.',
  ['l','ɭ','ɰ']),

// ===== VOWELS =====
'i': s('i','Close front unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.75,frontness:0.9}, tongue_root:{advancement:0.65}, lips:{rounding:0,openness:0.15,protrusion:0,spread:0.6}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['see','feet','happy'],fr:['si','lit'],de:['Biene','ihn'],es:['si','cinco'],it:['si','vino'],ja:['iki']},
  'Tongue as high and far forward as possible without creating friction. Lips spread. The "ee" in "see". Most languages have this vowel.',
  ['ɪ','y','e'], {height:'close',backness:'front',rounded:false}),

'y': s('y','Close front rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.75,frontness:0.9}, tongue_root:{advancement:0.65}, lips:{rounding:0.8,openness:0.15,protrusion:0.3,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {fr:['lune','tu','rue'],de:['über','Tür','grün']},
  'Like /i/ but with rounded lips. French "u" in "tu", German "ü". Tell actors: say "ee" and round your lips tightly without moving your tongue. This is the hardest vowel for English speakers — they tend to back the tongue to /u/.',
  ['i','u','ʏ','ø'], {height:'close',backness:'front',rounded:true}),

'ɨ': s('ɨ','Close central unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.75,frontness:0.5}, tongue_root:{advancement:0.50}, lips:{rounding:0,openness:0.15,protrusion:0,spread:0.3}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {ru:['ты','был'],ro:['în'],pl:['być']},
  'High central vowel, unrounded. Russian "ы". Between /i/ and /ɯ/. Tell actors: say "ee" but pull the tongue back to the middle of the mouth.',
  ['i','ʉ','ɯ'], {height:'close',backness:'central',rounded:false}),

'ʉ': s('ʉ','Close central rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.75,frontness:0.5}, tongue_root:{advancement:0.50}, lips:{rounding:0.8,openness:0.15,protrusion:0.3,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {sv:['hus'],no:['hus']},
  'High central rounded. Swedish and Norwegian "u" in some contexts. Like /u/ with the tongue further forward.',
  ['ɨ','u','y'], {height:'close',backness:'central',rounded:true}),

'ɯ': s('ɯ','Close back unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.75,frontness:0.1}, tongue_root:{advancement:0.50}, lips:{rounding:0,openness:0.15,protrusion:0,spread:0.3}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {ja:['寿司 (su in sushi)'],ko:['으'],tr:['kız']},
  'Like /u/ but without lip rounding. Japanese "u" is close to this. Korean "ㅡ". Tell actors: say "oo" but keep your lips completely relaxed and spread.',
  ['u','ɨ','ɤ'], {height:'close',backness:'back',rounded:false}),

'u': s('u','Close back rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.75,frontness:0.1}, tongue_root:{advancement:0.65}, lips:{rounding:0.9,openness:0.15,protrusion:0.4,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['food','blue','shoe'],fr:['ou','tout','rouge'],de:['Schuh','gut'],es:['tu','luna'],it:['luna','uno'],ja:['(approximated)']},
  'Tongue high and back, lips tightly rounded and protruded. The "oo" in "food". Very common across languages. English /u/ has more diphthongization than most languages.',
  ['ʊ','ɯ','o'], {height:'close',backness:'back',rounded:true}),

'e': s('e','Close-mid front unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.60,frontness:0.85}, tongue_root:{advancement:0.60}, lips:{rounding:0,openness:0.2,protrusion:0,spread:0.4}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {fr:['été','les'],de:['Beet','Weg'],es:['mesa','pero'],it:['sera','che'],ja:['eki']},
  'Mid-high front vowel, lips spread. Not quite as high as /i/. French "é", German long "e", Spanish "e". English doesn\'t have a pure /e/ — English "ay" is the diphthong /eɪ/.',
  ['ɛ','i','ø'], {height:'close-mid',backness:'front',rounded:false}),

'ø': s('ø','Close-mid front rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.60,frontness:0.85}, tongue_root:{advancement:0.60}, lips:{rounding:0.7,openness:0.2,protrusion:0.25,spread:0}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {fr:['peu','deux','bleu'],de:['schön','Goethe']},
  'Like /e/ with rounded lips. French "eu" in "peu", German "ö" in "schön". Tell actors: say "ay" and round your lips without moving the tongue.',
  ['e','œ','y'], {height:'close-mid',backness:'front',rounded:true}),

'ɘ': s('ɘ','Close-mid central unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.60,frontness:0.5}, tongue_root:{advancement:0.50}, lips:{rounding:0,openness:0.2,protrusion:0,spread:0.2}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {},
  'Central mid-high vowel. Relatively rare as a distinct phoneme. Close to schwa but higher.',
  ['ə','e','ɵ'], {height:'close-mid',backness:'central',rounded:false}),

'ɵ': s('ɵ','Close-mid central rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.60,frontness:0.5}, tongue_root:{advancement:0.50}, lips:{rounding:0.6,openness:0.2,protrusion:0.2,spread:0}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {sv:['full']},
  'Central mid-high rounded. Swedish short "u". Between /ø/ and /o/ in tongue position.',
  ['ɘ','ø','o'], {height:'close-mid',backness:'central',rounded:true}),

'ɤ': s('ɤ','Close-mid back unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.60,frontness:0.15}, tongue_root:{advancement:0.50}, lips:{rounding:0,openness:0.2,protrusion:0,spread:0.2}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {ko:['거'],zh:['hé (河)']},
  'Like /o/ without rounding. Korean "ㅓ", some analyses of Mandarin vowels. Tell actors: say "oh" with completely relaxed, unrounded lips.',
  ['o','ɯ','ʌ'], {height:'close-mid',backness:'back',rounded:false}),

'o': s('o','Close-mid back rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.60,frontness:0.15}, tongue_root:{advancement:0.60}, lips:{rounding:0.75,openness:0.2,protrusion:0.3,spread:0}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {fr:['eau','beau','mot'],de:['Boot','Sohn'],es:['no','todo'],it:['sole','como'],ja:['otoko']},
  'Mid-high back rounded. French "eau", Spanish "o", German long "o". English doesn\'t have a pure /o/ — English "oh" is typically /oʊ/. Tell actors to keep the vowel PURE, no glide.',
  ['ɔ','u','ɤ'], {height:'close-mid',backness:'back',rounded:true}),

'ɛ': s('ɛ','Open-mid front unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.42,frontness:0.8}, tongue_root:{advancement:0.38}, lips:{rounding:0,openness:0.3,protrusion:0,spread:0.3}, jaw:{openness:0.35}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['bed','head','said'],fr:['fête','lait','père'],de:['Bett','Fest'],it:['bello','è']},
  'The "e" in "bed". Lower and more open than /e/. Very common in English. French "è" and "ê". Italian open "e" (è).',
  ['e','æ','œ'], {height:'open-mid',backness:'front',rounded:false}),

'œ': s('œ','Open-mid front rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.42,frontness:0.8}, tongue_root:{advancement:0.38}, lips:{rounding:0.65,openness:0.3,protrusion:0.2,spread:0}, jaw:{openness:0.35}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {fr:['peur','sœur','beurre'],de:['Hölle','zwölf']},
  'Like /ɛ/ with rounded lips. French "eu" in "peur" (open syllable "eu" is /ø/). German short "ö". Tell actors: say "eh" and round the lips.',
  ['ɛ','ø','ɔ'], {height:'open-mid',backness:'front',rounded:true}),

'ɜ': s('ɜ','Open-mid central unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.42,frontness:0.5}, tongue_root:{advancement:0.50}, lips:{rounding:0,openness:0.3,protrusion:0,spread:0.15}, jaw:{openness:0.35}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['bird','nurse','her (RP)']},
  'The vowel in RP "bird", "nurse", "her". Central, mid-open. American English adds r-coloring to get [ɝ]. Tell actors doing RP: the tongue is central and relaxed, no lip rounding, no retroflexion.',
  ['ə','ɛ','ʌ'], {height:'open-mid',backness:'central',rounded:false}),

'ɞ': s('ɞ','Open-mid central rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.42,frontness:0.5}, tongue_root:{advancement:0.50}, lips:{rounding:0.6,openness:0.3,protrusion:0.15,spread:0}, jaw:{openness:0.35}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {},
  'Central mid-open rounded. Rare as a distinct phoneme. Some analyses of Irish English vowels use this symbol.',
  ['ɜ','œ','ɔ'], {height:'open-mid',backness:'central',rounded:true}),

'ʌ': s('ʌ','Open-mid back unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.42,frontness:0.25}, tongue_root:{advancement:0.40}, lips:{rounding:0,openness:0.3,protrusion:0,spread:0.1}, jaw:{openness:0.35}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['cut','strut','bus','love'],ko:['어 (some analyses)']},
  'The vowel in "cut", "strut", "bus". Back-central, mid-open, unrounded. In RP this has actually moved to a more central position. American and British realizations differ — RP is more central.',
  ['ɔ','ɑ','ə'], {height:'open-mid',backness:'back',rounded:false}),

'ɔ': s('ɔ','Open-mid back rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.42,frontness:0.15}, tongue_root:{advancement:0.38}, lips:{rounding:0.65,openness:0.35,protrusion:0.2,spread:0}, jaw:{openness:0.4}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['thought','law','all (RP)'],fr:['or','port','bonne'],de:['Sonne','Gott'],it:['cosa','otto']},
  'The vowel in RP "thought", "law", "all". Back, mid-open, rounded. Many American dialects merge this with /ɑ/ (cot-caught merger). French "o" in closed syllables.',
  ['o','ɑ','ʌ'], {height:'open-mid',backness:'back',rounded:true}),

'æ': s('æ','Near-open front unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.32,frontness:0.85}, tongue_root:{advancement:0.50}, lips:{rounding:0,openness:0.45,protrusion:0,spread:0.3}, jaw:{openness:0.5}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['cat','trap','bad']},
  'The vowel in "cat", "trap", "bad". Low front unrounded. Some American dialects raise and tense this before nasals ("man" sounds like "me-an"). Australian English has a very open realization.',
  ['a','ɛ','ɑ'], {height:'near-open',backness:'front',rounded:false}),

'a': s('a','Open front unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.2,frontness:0.75}, tongue_root:{advancement:0.50}, lips:{rounding:0,openness:0.55,protrusion:0,spread:0.2}, jaw:{openness:0.6}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {fr:['patte','la'],de:['Mann','Kamm'],es:['casa','pan'],it:['casa','la'],ja:['aka']},
  'Open front vowel. Spanish "a", Italian "a", French "a" in "patte". The most open vowel — jaw drops wide, tongue lies flat and low. More front than English /ɑ/.',
  ['ɑ','æ','ɶ'], {height:'open',backness:'front',rounded:false}),

'ɶ': s('ɶ','Open front rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.2,frontness:0.75}, tongue_root:{advancement:0.50}, lips:{rounding:0.7,openness:0.5,protrusion:0.2,spread:0}, jaw:{openness:0.6}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {},
  'Like /a/ with lip rounding. Very rare. Some analyses of Danish and Swedish use this symbol.',
  ['a','œ','ɒ'], {height:'open',backness:'front',rounded:true}),

'ɑ': s('ɑ','Open back unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.2,frontness:0.15}, tongue_root:{advancement:0.30}, lips:{rounding:0,openness:0.55,protrusion:0,spread:0.1}, jaw:{openness:0.6}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['father','palm','spa'],fr:['pâte']},
  'Open back unrounded. The "ah" in "father", "spa". Further back than /a/. American English PALM/LOT vowel. RP "bath" words use this in Southern British English.',
  ['a','ɒ','ʌ'], {height:'open',backness:'back',rounded:false}),

'ɒ': s('ɒ','Open back rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.2,frontness:0.15}, tongue_root:{advancement:0.30}, lips:{rounding:0.6,openness:0.5,protrusion:0.15,spread:0}, jaw:{openness:0.6}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['lot','cloth','hot (RP)']},
  'Open back rounded. RP "lot", "cloth", "hot". Not used in most American English (merged with /ɑ/). Like /ɑ/ but with slight lip rounding. Very important for distinguishing RP from General American.',
  ['ɑ','ɔ','a'], {height:'open',backness:'back',rounded:true}),

'ɪ': s('ɪ','Near-close near-front unrounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.68,frontness:0.8}, tongue_root:{advancement:0.38}, lips:{rounding:0,openness:0.18,protrusion:0,spread:0.4}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['kit','bit','sit'],de:['mit','bitte']},
  'The vowel in "kit", "bit". Slightly lower and more central than /i/. English uses this for short "i". German short "i" is also [ɪ]. Common mistake: using tense /i/ where lax /ɪ/ is needed.',
  ['i','e','ʏ'], {height:'near-close',backness:'near-front',rounded:false}),

'ʏ': s('ʏ','Near-close near-front rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.68,frontness:0.8}, tongue_root:{advancement:0.38}, lips:{rounding:0.7,openness:0.18,protrusion:0.2,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {de:['hübsch','fünf']},
  'Like /ɪ/ with rounded lips. German short "ü" as in "fünf", "hübsch".',
  ['ɪ','y','ø'], {height:'near-close',backness:'near-front',rounded:true}),

'ʊ': s('ʊ','Near-close near-back rounded vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.68,frontness:0.25}, tongue_root:{advancement:0.35}, lips:{rounding:0.7,openness:0.18,protrusion:0.25,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['foot','put','book'],de:['und','Mutter']},
  'The vowel in "foot", "put", "book". Lower and more central than /u/. English short "oo". German short "u".',
  ['u','o','ɪ'], {height:'near-close',backness:'near-back',rounded:true}),

'ɐ': s('ɐ','Near-open central vowel','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.30,frontness:0.5}, tongue_root:{advancement:0.50}, lips:{rounding:0,openness:0.45,protrusion:0,spread:0.1}, jaw:{openness:0.5}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {de:['besser (final)'],pt:['cada']},
  'Near-open central. German unstressed "-er" ending is [ɐ]. Some varieties of Portuguese use this. Between /ə/ and /a/ in height.',
  ['ə','a','ʌ'], {height:'near-open',backness:'central',rounded:false}),

'ə': s('ə','Mid central vowel (schwa)','vowel','vowel','vowel',true,
  a({ tongue_body:{height:0.50,frontness:0.5}, tongue_root:{advancement:0.50}, lips:{rounding:0,openness:0.25,protrusion:0,spread:0.1}, jaw:{openness:0.25}, vocal_folds:{vibrating:true} }),
  {type:'vowel',path:'oral',constriction_point:'none'},
  {en:['about','sofa','the (unstressed)'],fr:['le','de'],de:['bitte (final e)']},
  'THE most common vowel in English — every unstressed vowel tends toward schwa. Completely neutral: tongue mid-height, mid-central, lips neutral. "The lazy vowel." Found in the first syllable of "about", second syllable of "sofa". French "e muet" in "le".',
  ['ɐ','ɜ','ʌ'], {height:'mid',backness:'central',rounded:false}),

// ===== AFFRICATES =====
't͡ʃ': s('t͡ʃ','Voiceless postalveolar affricate','affricate','postalveolar','affricate',false,
  a({ tongue_tip:{target:'postalveolar',contact:true,x:0.80,y:1.0}, tongue_blade:{x:0.70,y:0.65}, tongue_body:{height:0.55,frontness:0.58}, lips:{rounding:0.20,openness:0.15,protrusion:0.10,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:false} }),
  {type:'affricate',path:'oral',constriction_point:'postalveolar'},
  {en:['church','match','nature'],it:['ciao','cena'],es:['mucho','chico'],de:['Deutsch']},
  'Starts as /t/ (full closure) then releases into /ʃ/ (friction). English "ch". The closure and release must be at the SAME place — postalveolar. Common mistake: making the closure too far forward (alveolar /t/ + postalveolar /ʃ/ = two separate sounds).',
  ['d͡ʒ','ʃ','t']),

'd͡ʒ': s('d͡ʒ','Voiced postalveolar affricate','affricate','postalveolar','affricate',true,
  a({ tongue_tip:{target:'postalveolar',contact:true,x:0.80,y:1.0}, tongue_blade:{x:0.70,y:0.65}, tongue_body:{height:0.55,frontness:0.58}, lips:{rounding:0.20,openness:0.15,protrusion:0.10,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'affricate',path:'oral',constriction_point:'postalveolar'},
  {en:['judge','age','gem'],it:['giorno','gente']},
  'Voiced version of /t͡ʃ/. English "j", "g" before front vowels. Italian "gi". Same place as /t͡ʃ/ but with voicing throughout.',
  ['t͡ʃ','ʒ','d']),

't͡s': s('t͡s','Voiceless alveolar affricate','affricate','alveolar','affricate',false,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_blade:{x:0.72,y:0.65}, tongue_body:{height:0.45,frontness:0.60}, jaw:{openness:0.12}, vocal_folds:{vibrating:false} }),
  {type:'affricate',path:'oral',constriction_point:'alveolar'},
  {de:['Zeit','Katze','Zug'],it:['pizza','forza'],ja:['tsunami'],zh:['cā (擦)']},
  'Alveolar stop /t/ releasing into /s/. German "z" and "tz". Italian "zz" in "pizza". English has this in "cats" but not as a single phoneme. Tell actors: the release must be sibilant — you should hear the /s/ hiss.',
  ['d͡z','s','t']),

'd͡z': s('d͡z','Voiced alveolar affricate','affricate','alveolar','affricate',true,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_blade:{x:0.72,y:0.65}, tongue_body:{height:0.45,frontness:0.60}, jaw:{openness:0.12}, vocal_folds:{vibrating:true} }),
  {type:'affricate',path:'oral',constriction_point:'alveolar'},
  {it:['zero','azzurro'],ja:['(none)']},
  'Voiced /t͡s/. Italian voiced "z" in "zero". Less common than its voiceless counterpart.',
  ['t͡s','z','d']),

't͡ɕ': s('t͡ɕ','Voiceless alveolo-palatal affricate','affricate','postalveolar','affricate',false,
  a({ tongue_tip:{target:'postalveolar',contact:true,x:0.80,y:1.0}, tongue_blade:{x:0.70,y:0.65}, tongue_body:{height:0.70,frontness:0.72}, jaw:{openness:0.12}, vocal_folds:{vibrating:false} }),
  {type:'affricate',path:'oral',constriction_point:'alveolo-palatal'},
  {zh:['jī (鸡)'],ja:['chi (ち)'],pl:['ć','ciasto'],ko:['ㅈ']},
  'Alveolo-palatal affricate. Mandarin "j", Japanese "ch" before "i", Polish "ć". More palatal than /t͡ʃ/ — the tongue body is higher.',
  ['d͡ʑ','t͡ʃ','ɕ']),

'd͡ʑ': s('d͡ʑ','Voiced alveolo-palatal affricate','affricate','postalveolar','affricate',true,
  a({ tongue_tip:{target:'postalveolar',contact:true,x:0.80,y:1.0}, tongue_blade:{x:0.70,y:0.65}, tongue_body:{height:0.70,frontness:0.72}, jaw:{openness:0.12}, vocal_folds:{vibrating:true} }),
  {type:'affricate',path:'oral',constriction_point:'alveolo-palatal'},
  {ja:['ji (じ)'],pl:['dź','dzień']},
  'Voiced alveolo-palatal affricate. Japanese "j" before "i", Polish "dź".',
  ['t͡ɕ','d͡ʒ','ʑ']),

// ===== CO-ARTICULATED =====
'w': s('w','Voiced labial-velar approximant','coarticulated','velar','approximant',true,
  a({ tongue_body:{height:0.60,frontness:0.20}, lips:{rounding:0.85,openness:0.15,protrusion:0.35,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'labial-velar'},
  {en:['wet','away','swim'],fr:['oui','Louis'],es:['huevo','bueno'],it:['uomo','fuoco']},
  'Simultaneous lip rounding AND tongue-back raising (two articulators at once). English "w". Essentially a non-syllabic /u/. Some languages lack /w/ — speakers may substitute /v/. French "ou" before vowels.',
  ['ʍ','v','u','ɥ']),

'ɥ': s('ɥ','Voiced labial-palatal approximant','coarticulated','palatal','approximant',true,
  a({ tongue_body:{height:0.68,frontness:0.80}, lips:{rounding:0.80,openness:0.15,protrusion:0.30,spread:0}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'approximant',path:'oral',constriction_point:'labial-palatal'},
  {fr:['huit','nuit','lui']},
  'Like /w/ but with a front tongue position — simultaneous lip rounding and tongue-front raising. French "u" before vowels: "huit", "nuit", "lui". Essentially a non-syllabic /y/. Tell actors: say French "u" (/y/) very quickly before a vowel.',
  ['w','j','y']),

// ===== CLICKS =====
'ʘ': s('ʘ','Bilabial click','click','bilabial','click',false,
  a({ tongue_body:{height:0.35,frontness:0.50}, lips:{rounding:0,openness:0,protrusion:0.1,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'click',path:'oral',constriction_point:'bilabial'},
  {},
  'A kissing sound. Lips seal, then the tongue pulls back creating suction, and the lip seal releases with a pop. Used in some Southern African languages.',
  ['ǀ','ǃ']),

'ǀ': s('ǀ','Dental click','click','dental','click',false,
  a({ tongue_tip:{target:'dental',contact:true,x:0.97,y:0.97}, tongue_body:{height:0.55,frontness:0.50}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'click',path:'oral',constriction_point:'dental'},
  {zu:['icici'],xh:['ixoxo']},
  'The "tsk tsk" disapproval sound. Tongue tip seals against the upper teeth while the back of the tongue seals against the velum. The front seal releases with a click. Used extensively in Zulu, Xhosa, and other Nguni languages.',
  ['ǃ','ǂ','ǁ']),

'ǃ': s('ǃ','Alveolar click','click','alveolar','click',false,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.55,frontness:0.50}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'click',path:'oral',constriction_point:'alveolar'},
  {zu:['iqaqa'],xh:['ukuqala']},
  'A sharp popping sound — like a bottle cork. Tongue tip seals at the alveolar ridge, back seal at velum, front seal releases sharply. Zulu "q", Xhosa "q". Louder and sharper than the dental click.',
  ['ǀ','ǂ','ǁ']),

'ǂ': s('ǂ','Palatal click','click','palatal','click',false,
  a({ tongue_body:{height:0.72,frontness:0.7}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'click',path:'oral',constriction_point:'palatal'},
  {},
  'Tongue blade seals against the palate, back seal at velum, front seal releases. Less common than dental and alveolar clicks.',
  ['ǀ','ǃ','ǁ']),

'ǁ': s('ǁ','Lateral click','click','alveolar','click',false,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.55,frontness:0.50}, tongue_sides:{lowered:true}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'click',path:'oral',constriction_point:'alveolar_lateral'},
  {zu:['idla'],xh:['ixhalanga']},
  'The sound used to encourage horses ("giddyup" click). Tongue tip seals at alveolar ridge, release is LATERAL — air rushes in from the sides. Zulu "x", Xhosa "x".',
  ['ǀ','ǃ','ɬ']),

// ===== IMPLOSIVES =====
'ɓ': s('ɓ','Voiced bilabial implosive','implosive','bilabial','plosive',true,
  a({ tongue_body:{height:0.35,frontness:0.50}, lips:{rounding:0,openness:0,protrusion:0.05,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:true} }),
  {type:'implosive',path:'oral',constriction_point:'bilabial'},
  {sw:['baba'],ha:['ɓara']},
  'Like /b/ but the larynx moves DOWN during closure, creating a suction effect. The release sounds "implosive" — air rushes inward. Found in Swahili, Hausa, Sindhi. Tell actors: say /b/ while pulling your larynx down (like the start of a yawn).',
  ['b','ɗ','p']),

'ɗ': s('ɗ','Voiced alveolar implosive','implosive','alveolar','plosive',true,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.60}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'implosive',path:'oral',constriction_point:'alveolar'},
  {sw:['dada'],ha:['ɗan']},
  'Alveolar implosive — like /d/ with larynx lowering. Swahili, Hausa, Vietnamese.',
  ['d','ɓ','t']),

'ʄ': s('ʄ','Voiced palatal implosive','implosive','palatal','plosive',true,
  a({ tongue_body:{height:0.72,frontness:0.80}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'implosive',path:'oral',constriction_point:'palatal'},
  {},
  'Palatal implosive. Rare. Found in some West African languages.',
  ['ɟ','ɗ','ɠ']),

'ɠ': s('ɠ','Voiced velar implosive','implosive','velar','plosive',true,
  a({ tongue_body:{height:0.65,frontness:0.30}, jaw:{openness:0.15}, vocal_folds:{vibrating:true} }),
  {type:'implosive',path:'oral',constriction_point:'velar'},
  {sw:['(rare)']},
  'Velar implosive — like /ɡ/ with larynx lowering. Less common than bilabial and alveolar implosives.',
  ['ɡ','ɓ','ɗ']),

'ʛ': s('ʛ','Voiced uvular implosive','implosive','uvular','plosive',true,
  a({ tongue_body:{height:0.58,frontness:0.15}, tongue_root:{advancement:0.35}, jaw:{openness:0.2}, vocal_folds:{vibrating:true} }),
  {type:'implosive',path:'oral',constriction_point:'uvular'},
  {},
  'Uvular implosive. Very rare. Found in some Mayan languages.',
  ['ɢ','ɠ']),

// ===== EJECTIVES =====
'pʼ': s('pʼ','Bilabial ejective','ejective','bilabial','plosive',false,
  a({ tongue_body:{height:0.35,frontness:0.50}, lips:{rounding:0,openness:0,protrusion:0.1,spread:0}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'ejective',path:'oral',constriction_point:'bilabial'},
  {am:['(Amharic)'],ka:['პური']},
  'Like /p/ but the larynx moves UP, compressing air above it. Released with a sharp, popping burst — higher pressure than pulmonic /p/. Found in Georgian, Amharic, many indigenous American languages. Tell actors: close your glottis AND your lips, then pop both open simultaneously.',
  ['p','tʼ','kʼ']),

'tʼ': s('tʼ','Alveolar ejective','ejective','alveolar','plosive',false,
  a({ tongue_tip:{target:'alveolar_ridge',contact:true,x:0.87,y:1.0}, tongue_body:{height:0.45,frontness:0.60}, jaw:{openness:0.12}, vocal_folds:{vibrating:false} }),
  {type:'ejective',path:'oral',constriction_point:'alveolar'},
  {am:['(Amharic)'],ka:['თ vs ტ']},
  'Alveolar ejective. Tongue tip on alveolar ridge, glottis closed, larynx pushes up for release. Georgian distinguishes aspirated /tʰ/, ejective /tʼ/, and plain /t/.',
  ['t','pʼ','kʼ']),

'kʼ': s('kʼ','Velar ejective','ejective','velar','plosive',false,
  a({ tongue_body:{height:0.65,frontness:0.30}, jaw:{openness:0.12}, vocal_folds:{vibrating:false} }),
  {type:'ejective',path:'oral',constriction_point:'velar'},
  {am:['(Amharic)'],ka:['კაცი']},
  'Velar ejective. Back of tongue on velum, glottis closed, larynx pushes up. Very common in Caucasian and Ethiopian languages.',
  ['k','pʼ','tʼ']),

'sʼ': s('sʼ','Alveolar ejective fricative','ejective','alveolar','fricative',false,
  a({ tongue_tip:{target:'alveolar',contact:false,x:0.87,y:0.95}, tongue_blade:{x:0.72,y:0.65}, tongue_body:{height:0.48,frontness:0.62}, jaw:{openness:0.1}, vocal_folds:{vibrating:false} }),
  {type:'ejective_fricative',path:'oral',constriction_point:'alveolar'},
  {},
  'Ejective fricative — the glottis closes, larynx rises, and air is forced through the alveolar constriction. Rarer than ejective stops.',
  ['s','tʼ']),
};

// Vowel positions for the quadrilateral diagram (percentage x,y)
const vowelPositions = {
  'i':  {x:15,y:8},  'y':  {x:22,y:8},
  'ɨ':  {x:45,y:8},  'ʉ':  {x:52,y:8},
  'ɯ':  {x:78,y:8},  'u':  {x:85,y:8},

  'ɪ':  {x:25,y:22}, 'ʏ':  {x:32,y:22},
  'ʊ':  {x:72,y:22},

  'e':  {x:20,y:36}, 'ø':  {x:27,y:36},
  'ɘ':  {x:47,y:36}, 'ɵ':  {x:54,y:36},
  'ɤ':  {x:75,y:36}, 'o':  {x:82,y:36},

  'ə':  {x:50,y:50},

  'ɛ':  {x:25,y:60}, 'œ':  {x:32,y:60},
  'ɜ':  {x:48,y:60}, 'ɞ':  {x:55,y:60},
  'ʌ':  {x:72,y:60}, 'ɔ':  {x:79,y:60},

  'æ':  {x:32,y:76},
  'ɐ':  {x:50,y:76},

  'a':  {x:35,y:90}, 'ɶ':  {x:42,y:90},
  'ɑ':  {x:75,y:90}, 'ɒ':  {x:82,y:90},
};

const IPA_DATA = { sounds, places, manners, vowelPositions };
export default IPA_DATA;
